spring:
  application:
    name: spring-boot-validation
  http:
    encoding:
      force: true
  messages:
    basename: messages/message,message/message_ko_KR,message/message_en_US,messages/ValidationMessages,messages/ValidationMessages_ko_KR

server:
  port: 8888
